hash-format = "sha256"

[[files]]
file = "config/ftbquests/quests/chapter_groups.snbt"
hash = "739539b4146abfddb28d18027abc040e62af3634552c3c8092d021545f0c08fe"

[[files]]
file = "config/ftbquests/quests/chapters/create.snbt"
hash = "ff652c935d59f85375bce36a69f3fba892a786f7852a0027c34d9d4cc3c65114"

[[files]]
file = "config/ftbquests/quests/chapters/farmers_delight.snbt"
hash = "32fbd6d7d5abcb6857174c6250e2b69d1e47c79379efc5e64bfbc8832ae742d7"

[[files]]
file = "config/ftbquests/quests/chapters/minecraft.snbt"
hash = "69cf3959a77a3175c0539a97fde9a97361c5647998a9d0d2f86344569096c086"

[[files]]
file = "config/ftbquests/quests/data.snbt"
hash = "c66d3cbdee6463dfe67d6175e14ebb2d8c350feecb877ef6cd1ef89bc2cb46eb"

[[files]]
file = "icon.png"
hash = "ddbfb1f26cff8720f5022d530786293a71554e6005fae0a94e63e0d720b115b4"

[[files]]
file = "mods/adventurez.pw.toml"
hash = "b3eccd4cf5e295af72a29ae0a081106ae9e42791a3180e15f766f1946455f04a"
metafile = true

[[files]]
file = "mods/amendments.pw.toml"
hash = "5b332b628f2bbb11afdc82f4a9d27ca3afde5ad2d21c590af5c7a080c2aa9dfa"
metafile = true

[[files]]
file = "mods/appleskin.pw.toml"
hash = "7d44149b8b22e0b19b082f49809edfc1b5f170e5d1d297cd73ae88c0b432c3ab"
metafile = true

[[files]]
file = "mods/architectury-api.pw.toml"
hash = "e12dce3e543168379a2856c66064ee2001e6420a9dfc6163f37b78e518947456"
metafile = true

[[files]]
file = "mods/better-quest-pop-up.pw.toml"
hash = "e0d6253a9d32f08d2643af7c9710ac062c2e256341dec0febcb408b643e494ac"
metafile = true

[[files]]
file = "mods/bosses-of-mass-destruction.pw.toml"
hash = "c603294c194b869fd14d2cdda3f0663f0137b1127b1fd2b627b3945854ef96c4"
metafile = true

[[files]]
file = "mods/cardinal-components-api.pw.toml"
hash = "0ed502ad7d53ca1936079cb7508b2e085909610ac51337fff2a3ce0fa6dcae28"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "41a3dc271859b118417946d2fdb2408523563b2f4f49048073672a342fb1aebf"
metafile = true

[[files]]
file = "mods/continuity.pw.toml"
hash = "ca80c5f6b0faca95bbc06192a3da36446ff396b5e6e0304f6779269b60bbdd9d"
metafile = true

[[files]]
file = "mods/create-fabric.pw.toml"
hash = "7d227ef90b1918ceb348ade235a5d17c7894acbf387575e96c08920a5bad1bbb"
metafile = true

[[files]]
file = "mods/create-questing.pw.toml"
hash = "e8a923898a025c633a45602876326a245aa78fd74707653e4f92e1d48efeba56"
metafile = true

[[files]]
file = "mods/cristel-lib.pw.toml"
hash = "6ec7fc70c84dc7f7f4578a85480264d82336d64ac0d8c95c0fcc55d350f64ab7"
metafile = true

[[files]]
file = "mods/deeperdarker.pw.toml"
hash = "3f352f4d2bd17152dc5d39010fb409c75f84e8ae9d8fd0d5da1e331b60e01999"
metafile = true

[[files]]
file = "mods/eldritch-mobs.pw.toml"
hash = "932c40da042c3d3d916b901733c676b5456e0c7aae63452c3ae1273ee19a51ed"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "2b7949e506ba69c57139127c0ccc6caf5a9ec5ec97788b81288118db3d7c2ad3"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/fabric-seasons-terralith-compat.pw.toml"
hash = "751b5e7213feb2072ee728327dcbb58134add5c5b0441c866dc0aa9fa1255e3b"
metafile = true

[[files]]
file = "mods/fabric-seasons.pw.toml"
hash = "ce276e188fa22c4b8e4a99a0558844284fff7d49af2c5e6683290eaa598a7c61"
metafile = true

[[files]]
file = "mods/farmers-delight-refabricated.pw.toml"
hash = "e09385ac1a1c0900b8fa619290eb0f0539949ebbc59f7604a7699485784ccc85"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "86cbfa8adbbb8be527f95aca49b427f892aa780773df141dfd7f4ffd02740bbd"
metafile = true

[[files]]
file = "mods/ftb-library-fabric-2001.2.12.jar"
hash = "d0f868c1d9bbf5a8bf681ff411cb71a4057e27cc70d71e0f115eef2a259511d4"

[[files]]
file = "mods/ftb-quests-fabric-2001.4.17.jar"
hash = "63bbebe03ed01f857b457338aec0cd2feb640578709bcd774b315efd665d8060"

[[files]]
file = "mods/ftb-teams-fabric-2001.3.1.jar"
hash = "37d213480a558453d196a7837b6a44fb3006e61cd4bf3a6d86c2d25243ebb1c8"

[[files]]
file = "mods/geckolib.pw.toml"
hash = "21d2df923fa369d69a40d69f6466153146bf403367430eaeb2569c1554857df8"
metafile = true

[[files]]
file = "mods/indium.pw.toml"
hash = "cb85864ff2d3936a5ab4f7e7ccf763dbda0153412ba52c95a63b29677a012aaf"
metafile = true

[[files]]
file = "mods/iris.pw.toml"
hash = "99efc9e805ce2888680d3cacb9be65733c6d4a8cfcb77e1976205f758db24346"
metafile = true

[[files]]
file = "mods/jade.pw.toml"
hash = "d5faaf6d7e4be8bdf9b1b200edee175c2704ce13abad9d1951a4d4a45b432d4e"
metafile = true

[[files]]
file = "mods/krypton.pw.toml"
hash = "9063bac3fdf585a43d318e3f9773475a28ecb8fe80bc7689cc480851eef97420"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "c8695e51366b601c5e9118a5d5650d234cc25fc8d1f90ebd186c17c199ba7fca"
metafile = true

[[files]]
file = "mods/lithostitched-fabric-1.20.1-1.4.11.jar"
hash = "78c13369bd34be50faee673a0618871bb9314443fcd506d8bf5457c3f95d02c4"

[[files]]
file = "mods/lithostitched.pw.toml"
hash = "55167e582fd4841cd6c581beb53d341e94285c216e04b1d7bff0068e875be2a6"
metafile = true

[[files]]
file = "mods/macaws-doors.pw.toml"
hash = "ea9af51413113483ba002f9827a66653b184363c68d6280009677df1fe171afa"
metafile = true

[[files]]
file = "mods/macaws-fences-and-walls.pw.toml"
hash = "35c812e91d098b979ce4618ceee0ffc3adc3d857d234c99735977e0ac337d8bb"
metafile = true

[[files]]
file = "mods/macaws-furniture.pw.toml"
hash = "0f170663bb0f70d773ac5c3d24f09747253c5ba8a855b3a45fe7f1952e574b78"
metafile = true

[[files]]
file = "mods/macaws-holidays.pw.toml"
hash = "030e3a4ea7c6598442cf5c9b9c3a4b5748b03b2477c3d5593cd0f734862a394c"
metafile = true

[[files]]
file = "mods/macaws-lights-and-lamps.pw.toml"
hash = "a6ffaf3b24a1312d3737417d70b20bb8b7c2d034851a24f672096380afe57dae"
metafile = true

[[files]]
file = "mods/macaws-roofs.pw.toml"
hash = "4a7a7460f802eaf18bb298e31c4925a38e5e649ff11b08c61a5f88c03b886749"
metafile = true

[[files]]
file = "mods/macaws-stairs.pw.toml"
hash = "c0262f9744dd166ad1264c436f355be3c1ab170487db78b42b6ebabe64f84a24"
metafile = true

[[files]]
file = "mods/macaws-trapdoors.pw.toml"
hash = "b186afdeb0bc341f38c57a30b90440e6b4c88f5f8417ba788a6efe1078171720"
metafile = true

[[files]]
file = "mods/macaws-windows.pw.toml"
hash = "cca59c22f3d72c86e6f33ab6497d7ce8a927aeff2517d7e4415602c623013bc3"
metafile = true

[[files]]
file = "mods/modid-1.0.0.jar"
hash = "e94bee24644e4516d6b28050fd46ff516314a1557f7cb4342143a368d2fa061b"

[[files]]
file = "mods/modmenu.pw.toml"
hash = "d7145fd1bd8b4bb6a3b84652a96a68870fb3ab32230f27520bb9362fd17ec39f"
metafile = true

[[files]]
file = "mods/moonlight.pw.toml"
hash = "d8a2ea4edf1c55f6fe01cbcc220543f056b91c0d79512e96df22e4259b7c5777"
metafile = true

[[files]]
file = "mods/mouse-tweaks.pw.toml"
hash = "b6685e98fce8f1f45868b9df3dbaa410ec23bb64896c826be596d98b01326116"
metafile = true

[[files]]
file = "mods/necronomicon.pw.toml"
hash = "0a51aa853f7ec0323cabc98e9c6957e35f8e8581f1ee5ce12eb95d0e98665fc2"
metafile = true

[[files]]
file = "mods/nyfs-spiders.pw.toml"
hash = "0e4b66acb56a69961e0324eb902df9f490b8681b3d3f99ac3f96bb1b55ad1ba9"
metafile = true

[[files]]
file = "mods/owo-lib.pw.toml"
hash = "df4c4fe3aff1792aa7d19d097d5d1bc0c6e958e6e4ee32dbf148ecac62e1274d"
metafile = true

[[files]]
file = "mods/remove-terralith-intro-message.pw.toml"
hash = "fe85eb7e13d32999eb376d154be220d82134c534a3f066fa263fb4af11535232"
metafile = true

[[files]]
file = "mods/sanity-descent-into-madness.pw.toml"
hash = "2297e5ef425cbcfe1cc941083389fc5d3a48e2c1c6bee98e521d4cca1673ad18"
metafile = true

[[files]]
file = "mods/servercore.pw.toml"
hash = "058f62395b41a3b18121bcd961320cc8fd8460a34a5ccb4f07552e42ff19df4a"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "6225a36557ab2dfd1c4d3fb3c0868ed61c465d3246695b10ff10d339f65e3302"
metafile = true

[[files]]
file = "mods/simplechat-fork++.pw.toml"
hash = "d5a50b2d41bd6d55aff728ef0b272ab6d22d82dd7dcf5d1bb6dad6188c2d030c"
metafile = true

[[files]]
file = "mods/slabs-expanded.pw.toml"
hash = "1f832a42c7922284e8bc259af0e584a8470ac8a27fc1f4a86003192ee18ccd60"
metafile = true

[[files]]
file = "mods/slice-and-dice.pw.toml"
hash = "47493d398295964924d386d0fb866dac1a2d5e0cd4692b8436ea2552ce6c99f6"
metafile = true

[[files]]
file = "mods/sodium.pw.toml"
hash = "ecf8e1df2361e5f1d090f83eee16c449ff1021dfb2da46474a72726406d5d535"
metafile = true

[[files]]
file = "mods/sound-physics-remastered.pw.toml"
hash = "5cd3420078c7c24bf7414c7243a69b2d2a21c3c5e29150444697b11a001c44d8"
metafile = true

[[files]]
file = "mods/supplementaries.pw.toml"
hash = "3135bb6ec401e951d248de79dbdf40608e362e64b89fe9e7d2e74399f3b49375"
metafile = true

[[files]]
file = "mods/terralith-restoned.pw.toml"
hash = "6fce1ec54d9b11eeb07de3951ac823ba52b9021fa420650e8e16c9bfc3302135"
metafile = true

[[files]]
file = "mods/terralith.pw.toml"
hash = "3b61fcf1c80cfdd79282be71ddfa9cce02fc13f8d87a760db455e2a97b801f40"
metafile = true

[[files]]
file = "mods/the-graveyard-fabric.pw.toml"
hash = "bd31e70accc06b28c16c83cc021ca715c853aed78565b58be3c269c17de6730c"
metafile = true

[[files]]
file = "mods/towns-and-towers.pw.toml"
hash = "7b7108d879e1e1c141b24d0d8fa268a6bbcd5c227875d156fcc62c3beec55f63"
metafile = true

[[files]]
file = "mods/when-dungeons-arise.pw.toml"
hash = "a4f596b65b72b0c718e35cfb2e1a36e1887438b44a39daeec75a1c725a0441c4"
metafile = true

[[files]]
file = "mods/whisperwoods.pw.toml"
hash = "5e578325a749b02bfef2dceb64d3334b1610b9a59c3b057c67a6407d2f1c1cd8"
metafile = true

[[files]]
file = "mods/xaeros-minimap.pw.toml"
hash = "d33719fa79b683a327acafbe1e2617482b5a3272fd471bb822a72314d3cd511f"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "31938394e90226cd1529b7be0283394bf2eb7814a8e4f5488879bf75c6945ab8"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "8305bf17272f0c579b0930b751c12089de9fb157dbdb5c080836ce3daad310b5"
metafile = true

[[files]]
file = "mods/zoomify.pw.toml"
hash = "d2d5a9c835661b4f6f718fd057f03594b87aa49d1bcd9711af8553e51ea4a6fb"
metafile = true

[[files]]
file = "servers.dat"
hash = "cf464b286d403f9ba4d4f39b1472d6631177a8816642aca033d0cdb7ecad2a4b"
